# Generated by Django 3.2.6 on 2021-08-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('kanji_example', models.CharField(blank=True, max_length=50, null=True)),
                ('kanji_gif', models.CharField(blank=True, max_length=50, null=True)),
                ('reading_example_first', models.CharField(blank=True, max_length=50, null=True)),
                ('reading_example_second', models.CharField(blank=True, max_length=50, null=True)),
                ('words_example', models.JSONField(blank=True, null=True)),
                ('words_translated_example', models.JSONField(blank=True, null=True)),
                ('transcription', models.CharField(blank=True, max_length=50, null=True)),
                ('lessons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wakaranai.book')),
            ],
        ),
    ]
