# Generated by Django 3.2.6 on 2021-08-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wakaranai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lessons',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='kanji_gif',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reading_example_first',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reading_example_second',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='words_example',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='words_translated_example',
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_gif', models.CharField(blank=True, max_length=50, null=True)),
                ('reading_example_first', models.CharField(blank=True, max_length=50, null=True)),
                ('reading_example_second', models.CharField(blank=True, max_length=50, null=True)),
                ('words_example', models.JSONField(blank=True, null=True)),
                ('words_translated_example', models.JSONField(blank=True, null=True)),
                ('transcription', models.CharField(blank=True, max_length=50, null=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wakaranai.lesson')),
            ],
        ),
    ]
