# Generated by Django 3.2.6 on 2021-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakaranai', '0002_auto_20210808_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
